# Generated by Django 5.0.6 on 2024-05-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
