# Generated by Django 5.0.1 on 2024-01-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='is_available_for_commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artists.artistprofile'),
        ),
    ]
